# Generated by Django 5.0.14 on 2026-06-03 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobpayment',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=5000.0, max_digits=10),
        ),
    ]
